server:
  port: 9090

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://user-service-db.cen6mm82657u.us-east-1.rds.amazonaws.com:5432/postgres
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    info:
      title: User Service API
      description: API documentation for User Service
      version: 1.0.0 # This is the version of your API

logging:
  level:
    org.springdoc: DEBUG