name: Build and Deploy to AWS

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # --- CI: Build and Push to ECR ---
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push to Amazon ECR
        id: build-image
        run: |
          docker build -t user-service .
          docker tag user-service:latest ${{ steps.login-ecr.outputs.registry }}/myproject/user-service:latest
          docker push ${{ steps.login-ecr.outputs.registry }}/myproject/user-service:latest


      # -- Verify key format before SSH Test
      - name: Verify Key Format
        run: |
          echo "Key content (first 3 chars): ${SECRET_KEY:0:3}"
          echo "Key length: ${#SECRET_KEY}"
        env:
          SECRET_KEY: ${{ secrets.EC2_SSH_KEY }}

      # --- Pre-Deployment Connection Test ---
      - name: Test SSH Connection to EC2
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan ${{ secrets.EC2_IP }} >> ~/.ssh/known_hosts
          ssh -i <(echo "${{ secrets.EC2_SSH_KEY }}") \
            -o StrictHostKeyChecking=no \
            -o UserKnownHostsFile=/dev/null \
            ec2-user@${{ secrets.EC2_IP }} "echo 'SSH connection successful!'; docker --version"

      # --- CD: Deploy to EC2 ---
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_IP }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          timeout: 60s
          script: |
            # Pull Docker image
            aws ecr get-login-password --region us-east-1 | \
              docker login --username AWS --password-stdin ${{ steps.login-ecr.outputs.registry }}

            docker pull ${{ steps.login-ecr.outputs.registry }}/myproject/user-service:latest

            # Stop old container
            docker stop user-service || true
            docker rm user-service || true

            # Run new container with DB config
            docker run -d \
              --name user-service \
              -e SPRING_DATASOURCE_URL="jdbc:postgresql://user-service-db.cen6mm82657u.us-east-1.rds.amazonaws.com:5432/user_service_db" \
              -e SPRING_DATASOURCE_USERNAME="app_user" \
              -e SPRING_DATASOURCE_PASSWORD="${{ secrets.DB_PASSWORD }}" \
              -p 8080:8080 \
              ${{ steps.login-ecr.outputs.registry }}/myproject/user-service:latest